### ISSUE TITLE
有权限 但是不能运行 什么情况

### ISSUE THREAD

**Issue by tjs101** [icodesign/Potatso#101]
![image](https://cloud.githubusercontent.com/assets/1590125/18119770/e23bdae4-6f8e-11e6-9fbe-e14c691d57f1.png)

**Comment by jackyzh** [comment]
很多种情况会出现这样的问题，网上搜一下就好了。

比如 ：
- 你的手机没有加入开发者计划中的 device
- Capability 中的跟你开发者计划后台的不一致。

**Comment by GHYuan928** [comment]
有没有大神帮我看看如何回答这个比较好。苹果终于回复了Network Extension 的申请邮件。让我再描述app和将如何使用Network Extension Framework. 如何回答才不被拒绝呢？（其实就是Potatso,我想让它在手机上能运行起来，然后研究下这块的技术。）求好心人帮忙给个合适的回答

**Comment by azureplus** [comment]
用越狱设备，不然你要下载安装每一个mobileprovision

**Comment by welkinwalker** [comment]
同样的问题，网站找个各种解决方案都无果。
我仔细比较了 provisioning profile中的entitlement部分 和 工程里entitlement，是一样的

**Comment by qinxianjun163** [comment]
@tjs101 你编译成功了嘛

**Comment by azureplus** [comment]
编译成功，能在iOS设备上跑了
为嘛土豆丝很大，而surge 很小？
