### ISSUE TITLE
最新下载 git submodule update --init 完全没有反应

### ISSUE THREAD

**Issue by bf68** [icodesign/Potatso#105]
git submodule update --init 完全没有反应

**Comment by Comup-X** [comment]
fatal: Not a git repository (or any of the parent directories): .git
我是提示这个，是需要自己add？

**Comment by bf68** [comment]
@Comup-X 我试过创建也不行，只能自己下载一个放到对应的目录，但是这个错误解决了，后续还是有好多的错误，没法跑起来：((

**Comment by YuIosXiao** [comment]
@bf68 你编译成功了嘛？

**Comment by qinxianjun163** [comment]
@YuIosXiao 你也在编译嘛？

**Comment by bf68** [comment]
@YuIosXiao 不成功了。你成功吗？
