### ISSUE TITLE
ShadowPath.h file not found

### ISSUE THREAD

**Issue by YzsXQ** [icodesign/Potatso#115]
![error](https://cloud.githubusercontent.com/assets/13778722/19228995/c9d0277a-8efc-11e6-931f-82c3fa56bb73.png)

**Comment by qinxianjun163** [comment]
@YzsXQ 你好！请问你编译成功了嘛？

**Comment by YzsXQ** [comment]
@qinxianjun163 模拟器编译成功了,真机暂时没有权限,还在申请。

**Comment by qinxianjun163** [comment]
@YzsXQ 能否发我一份呢？

**Comment by qinxianjun163** [comment]
@YzsXQ 你是用swift3.0编译成功的吗？我打开之后有个convert，这个是否需要点击？你能远程帮我一下吗？
