### ISSUE TITLE
potatso VPN 启动后 http2 失效

### ISSUE THREAD

**Issue by imjustfly** [icodesign/Potatso#116]
potatso 向系统添加vpn之后， `NSURLSession`的 http2 就不能用了，访问http2的站点和api会降级到1.1。

断开vpn连接没有恢复 卸载应用没有恢复 重启设备能够恢复

在iOS 10.0.2上测试的。1台 iPhone 6 1台 iPad mini 2

**Comment by qinxianjun** [comment]
@imjustfly 你编译成功了嘛？你申请NE权限通过了嘛？需要多久？

**Comment by thomasbarwanitz** [comment]
Help iphone4

**Comment by thomasbarwanitz** [comment]
Help iphone4

**Comment by imjustfly** [comment]
@qinxianjun 没有 我从app store下载的
