### ISSUE TITLE
Specs satisfying the `CocoaLumberjack (~> 2.0.0)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by zicjin** [icodesign/Potatso#117]
error from:
bundle exec pod install

**Comment by guoshencheng** [comment]
so do i

**Comment by UnICorN21** [comment]
so do i, any solutions?

**Comment by alexei1118** [comment]
I resolved this error. Should specfify version at Podfile

pod 'LogglyLogger-CocoaLumberjack', '2.3.1'
pod 'CocoaLumberjack', '2.4.0'
