### ISSUE TITLE
不能打开youku 土豆 视频

### ISSUE THREAD

**Issue by garyZlot** [icodesign/Potatso#118]
AppStore 下载安装的可以播放youku视频，这套代码好不容易搞过，但不能播放youku的视频，一直转圈，然后就提示“当前网络忙。。。”

**Comment by qinxianjun163** [comment]
@garyZlot 你编译通过了？

**Comment by LuffyZWQ** [comment]
你好, 请问你真机上跑起来了吗, 我模拟器跑起来了, 当真机好像证书问题, 我是有权限的, 有什么细节可以告诉一下吗
