### ISSUE TITLE
我的有权限了,但是运行的时候提示一个问题(如下)

### ISSUE THREAD

**Issue by yuanshuoChen** [icodesign/Potatso#119]
切换VPN失败.(Error Domain = NSCocoaErrorDomain Code = 514 "未能存储该项目,因为该文件名称无效.")
运行的时候加入配置文件,然后连接出现上面的问题

**Comment by qinxianjun163** [comment]
@yuanshuoChen 您好！您可以帮我看一下我的问题嘛？我的企鹅791085038
