### ISSUE TITLE
运行崩溃

### ISSUE THREAD

**Issue by GHYuan928** [icodesign/Potatso#120]
![qq20161025-0 2x](https://cloud.githubusercontent.com/assets/12712718/19678022/9d758bba-9ace-11e6-89f8-d6d84d366292.png)

运行起来就crash。 打了全局断点也一样崩到这儿。

**Comment by yuanshuoChen** [comment]
你好,我的也是运行崩溃了,可以加一下QQ我们交流一下吗?(1130341213)
