### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by alexei1118** [icodesign/Potatso#122]
![screenshot](https://cloud.githubusercontent.com/assets/20523466/19804641/5fa87c78-9cc4-11e6-8042-604f9078b0b9.png)

Pod versions:
      - Alamofire, 3.5.1
      - Appirater, 2.0.5
      - Aspects, 0.0.1
      - AsyncSwift, 1.7.4
      - CallbackURLKit, 0.1.2
      - Cartography, 0.7.0
      - CocoaAsyncSocket, 7.4.3
      - CocoaLumberjack, 2.4.0
      - Crashlytics, 3.8.3
      - Eureka, 1.6.0
      - Fabric, 1.6.10
      - Helpshift, 5.6.1
      - ICDMaterialActivityIndicatorView, 0.1.2
      - ICSPullToRefresh, 0.4
      - ISO8601DateFormatter, 0.8
      - KeychainAccess, 2.4.0
      - KissXML, 5.1.2
      - LogglyLogger-CocoaLumberjack, 2.3.1
      - MBProgressHUD, 1.0.0
      - MMWormhole, 2.0.0
      - ObjectMapper, 1.5.0
      - PSOperations, 2.3.0 
      - Realm, 2.0.2
      - RealmSwift, 2.0.2
      - Reveal-iOS-SDK, 1.6.2
      - SwiftColor, 0.3.8

Xcode 7.3.1, MacOS X 10.11.6, Cocoapod 1.1.1

**Comment by LuffyZWQ** [comment]
@alexei1118 hello, I met the same issue . Did you fix ? would you mind tell me more detail ?
