### ISSUE TITLE
请问我按照#12的配置方式之后，每次代码都遇到了相同的错误

### ISSUE THREAD

**Issue by ifusernameif** [icodesign/Potatso#74]
![image](https://cloud.githubusercontent.com/assets/17850429/17389026/0509013a-5a33-11e6-8e5c-09521acca0bb.png)

我按照您的配置手册和 #12 #46  的配置方式进行了每一步的编译，包括下载 shadowsocks-libev 然后 ./configure 编译。三个 Target 的 identifier 和 描述文件也配置过，而且我也添加了 NetworkExtension 的 entitlements。

请问我现在的错误，是我哪里操作不正确吗？ 希望可以得到您的帮助

**Comment by vcan** [comment]
遇到同样的问题 请问解决了吗？

**Comment by LuffyZWQ** [comment]
recheck you xcode version , should be 7.3.1
