### ISSUE TITLE
添加“中国地区直连”规则组后，连接vpn成功，但是访问网站是自动断开

### ISSUE THREAD

**Issue by 731704267** [icodesign/Potatso#75]
为什么我在添加了“中国地区直连”规则组后，连接vpn成功，但是访问网站是自动断开，有人遇到相同的情况吗

**Comment by normalhh** [comment]
自动断开的问题不是在添加了那条规则后才有的。是在访问需要大量流量的网站，比如tumblr等会自动断线。作者根本不理会这个问题的。反馈了很多次了。所以不想用了，还是用6块钱的Shadowrocket靠谱

**Comment by 731704267** [comment]
不是的 我一点添加上中国地区直连，vpn连接成功一下就自己断开了

**Comment by 731704267** [comment]
一点天剑GEOIP的规则就无法连接vpn
