### ISSUE TITLE
添加GEOIP的规则后vpn无法连接

### ISSUE THREAD

**Issue by 731704267** [icodesign/Potatso#78]
添加使用GEOIP的规则后，点击连接后自动断开

**Comment by 731704267** [comment]
这个是奔溃日志



Incident Identifier: 57E3C920-8EBB-4291-A543-DB0926000AFF
CrashReporter Key:   2eba6c23d8ea251b8262aae7aad6595911fbc3b3
Hardware Model:      iPhone7,1
Process:             PacketTunnel [8493]
Path:                /private/var/containers/Bundle/Application/0E25931E-BF5F-45B5-97F5-D30050D6B6FF/Potatso.app/PlugIns/PacketTunnel.appex/PacketTunnel
Identifier:          com.touchingapp.Testpotatso.TestTunnel
Version:             114 (1.4.5)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2016-08-09 13:35:26.26 +0800
Launch Time:         2016-08-09 13:33:55.55 +0800
OS Version:          iOS 9.3.2 (13F69)
Report Version:      105

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  12

Filtered syslog:
None found

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_kernel.dylib        	0x0000000183460fd8 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x0000000183460e54 mach_msg + 72
2   CoreFoundation                	0x0000000183898c60 __CFRunLoopServiceMachPort + 196
3   CoreFoundation                	0x0000000183896964 __CFRunLoopRun + 1032
4   CoreFoundation                	0x00000001837c0c50 CFRunLoopRunSpecific + 384
5   Foundation                    	0x00000001841d0cfc -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 308
6   Foundation                    	0x0000000184226030 -[NSRunLoop(NSRunLoop) run] + 88
7   libxpc.dylib                  	0x0000000183584c64 _xpc_objc_main + 660
8   libxpc.dylib                  	0x00000001835869dc xpc_main + 200
9   Foundation                    	0x00000001843a3d60 service_connection_handler + 0
10  PlugInKit                     	0x000000018abe2c48 -[PKService run] + 544
11  PlugInKit                     	0x000000018abe28dc +[PKService main] + 56
12  PlugInKit                     	0x000000018abe2c6c +[PKService _defaultRun:arguments:] + 20
13  libextension.dylib            	0x00000001841b6058 NSExtensionMain + 64
14  libdyld.dylib                 	0x000000018335e8b8 start + 4

Thread 1 name:  Dispatch queue: com.apple.libdispatch-manager
Thread 1:
0   libsystem_kernel.dylib        	0x000000018347d4d8 kevent_qos + 8
1   libdispatch.dylib             	0x00000001833407d8 _dispatch_mgr_invoke + 232
2   libdispatch.dylib             	0x000000018332f648 _dispatch_source_invoke + 0

Thread 2:
0   libsystem_kernel.dylib        	0x000000018347cb48 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x0000000183545530 _pthread_wqthread + 1284
2   libsystem_pthread.dylib       	0x0000000183545020 start_wqthread + 4

Thread 3:
0   libsystem_kernel.dylib        	0x000000018347cb48 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x0000000183545530 _pthread_wqthread + 1284
2   libsystem_pthread.dylib       	0x0000000183545020 start_wqthread + 4

Thread 4:
0   libsystem_kernel.dylib        	0x000000018347cb48 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x0000000183545530 _pthread_wqthread + 1284
2   libsystem_pthread.dylib       	0x0000000183545020 start_wqthread + 4

Thread 5:
0   libsystem_kernel.dylib        	0x000000018347cb48 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x0000000183545530 _pthread_wqthread + 1284
2   libsystem_pthread.dylib       	0x0000000183545020 start_wqthread + 4

Thread 6:
0   libsystem_kernel.dylib        	0x000000018347c344 __select + 8
1   ShadowPath                    	0x00000001001d5350 select_poll (ev_select.c:170)
2   ShadowPath                    	0x00000001001d004c ev_run (ev.c:3522)
3   ShadowPath                    	0x000000010023e490 start_ss_local_server (local.c:1561)
4   PacketTunnel                  	0x0000000100055464 -[ProxyManager _startShadowsocks] (ProxyManager.m:127)
5   Foundation                    	0x00000001842b7e4c __NSThread__start__ + 1000
6   libsystem_pthread.dylib       	0x0000000183547b28 _pthread_body + 156
7   libsystem_pthread.dylib       	0x0000000183547a8c _pthread_body + 0
8   libsystem_pthread.dylib       	0x0000000183545028 thread_start + 4

Thread 7:
0   libsystem_kernel.dylib        	0x000000018347c344 __select + 8
1   ShadowPath                    	0x0000000100225bcc accept_connection (jbsockets.c:1359)
2   ShadowPath                    	0x00000001001c7b18 listen_loop (jcc.m:3442)
3   ShadowPath                    	0x00000001001c79dc shadowpath_main (jcc.m:3213)
4   PacketTunnel                  	0x0000000100055a2c -[ProxyManager _startHttpProxy:] (ProxyManager.m:168)
5   Foundation                    	0x00000001842b7e4c __NSThread__start__ + 1000
6   libsystem_pthread.dylib       	0x0000000183547b28 _pthread_body + 156
7   libsystem_pthread.dylib       	0x0000000183547a8c _pthread_body + 0
8   libsystem_pthread.dylib       	0x0000000183545028 thread_start + 4

Thread 8:
0   libsystem_kernel.dylib        	0x000000018347b068 __accept + 8
1   ShadowPath                    	0x0000000100202640 HandleRequest (an_main.m:117)
2   ShadowPath                    	0x0000000100202c34 realapp (an_main.m:239)
3   ShadowPath                    	0x0000000100202d14 an_main (an_main.m:265)
4   ShadowPath                    	0x00000001001c0184 -[AntinatServer start] (AntinatServer.m:40)
5   Foundation                    	0x00000001842b7e4c __NSThread__start__ + 1000
6   libsystem_pthread.dylib       	0x0000000183547b28 _pthread_body + 156
7   libsystem_pthread.dylib       	0x0000000183547a8c _pthread_body + 0
8   libsystem_pthread.dylib       	0x0000000183545028 thread_start + 4

Thread 9:
0   libsystem_kernel.dylib        	0x000000018347cb48 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x0000000183545530 _pthread_wqthread + 1284
2   libsystem_pthread.dylib       	0x0000000183545020 start_wqthread + 4

Thread 10:
0   libsystem_kernel.dylib        	0x000000018347cb48 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x0000000183545530 _pthread_wqthread + 1284
2   libsystem_pthread.dylib       	0x0000000183545020 start_wqthread + 4

Thread 11:
0   libsystem_kernel.dylib        	0x0000000183465528 kevent + 8
1   PacketProcessor               	0x0000000100466250 wait_for_events (BReactor_badvpn.c:428)
2   PacketProcessor               	0x0000000100465ec4 BReactor_Exec (BReactor_badvpn.c:770)
3   PacketProcessor               	0x0000000100454000 tun2socks_main (tun2socks.c:416)
4   PacketProcessor               	0x000000010046b5ec -[TunnelInterface _startTun2Socks:] (TunnelInterface.m:126)
5   Foundation                    	0x00000001842b7e4c __NSThread__start__ + 1000
6   libsystem_pthread.dylib       	0x0000000183547b28 _pthread_body + 156
7   libsystem_pthread.dylib       	0x0000000183547a8c _pthread_body + 0
8   libsystem_pthread.dylib       	0x0000000183545028 thread_start + 4

Thread 12 Crashed:
0   libsystem_kernel.dylib        	0x000000018347c11c __pthread_kill + 8
1   libsystem_pthread.dylib       	0x0000000183548ef8 pthread_kill + 112
2   libsystem_c.dylib             	0x00000001833ede4c __abort + 148
3   libsystem_c.dylib             	0x00000001833eddb8 __abort + 0
4   libsystem_c.dylib             	0x00000001833c2e7c basename + 0
5   ShadowPath                    	0x0000000100216abc record_info_for_database (maxminddb.c:977)
6   ShadowPath                    	0x00000001002165fc find_address_in_search_tree (maxminddb.c:879)
7   ShadowPath                    	0x0000000100216580 MMDB_lookup_sockaddr (maxminddb.c:867)
8   ShadowPath                    	0x00000001001ec00c forward_ip_routing (filters.c:2698)
9   ShadowPath                    	0x00000001001ec160 forward_ip (filters.c:2719)
10  ShadowPath                    	0x0000000100224748 rfc2553_connect_to (jbsockets.c:353)
11  ShadowPath                    	0x00000001002241e0 connect_to (jbsockets.c:183)
12  ShadowPath                    	0x0000000100224ef4 connect_to_forward (jbsockets.c:229)
13  ShadowPath                    	0x000000010022f388 forwarded_connect (gateway.c:604)
14  ShadowPath                    	0x00000001001c8cb8 chat (jcc.m:1920)
15  ShadowPath                    	0x00000001001c8038 serve (jcc.m:2843)
16  libsystem_pthread.dylib       	0x0000000183547b28 _pthread_body + 156
17  libsystem_pthread.dylib       	0x0000000183547a8c _pthread_body + 0
18  libsystem_pthread.dylib       	0x0000000183545028 thread_start + 4

Thread 12 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000001
    x4: 0x0000000000000000   x5: 0x0000000000989680   x6: 0x0000000000000027   x7: 0x000000013c612de0
    x8: 0x0000000008000000   x9: 0x0000000004000000  x10: 0x00000000000003e8  x11: 0x0000000000000000
   x12: 0x0000000000000039  x13: 0x000000000000000d  x14: 0x000000008000001f  x15: 0x0000000080000023
   x16: 0x0000000000000148  x17: 0x000000010036c060  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x000000016e61b000  x21: 0x00000000000003d1  x22: 0x000000010033a899  x23: 0x0000000100790000
   x24: 0x00000001a0a05000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000  fp: 0x000000016e618f90   lr: 0x0000000183548ef8
    sp: 0x000000016e618f70   pc: 0x000000018347c11c cpsr: 0x00000000

**Comment by laoyur** [comment]
同样的问题

挂在了maxminddb.c中以下函数的断言处：

```
LOCAL record_info_s record_info_for_database(MMDB_s *mmdb)
{
    record_info_s record_info = {
        .record_length       = mmdb->full_record_byte_size,
        .right_record_offset = 0
    };

    if (record_info.record_length == 6) {
        record_info.left_record_getter = &get_uint24;
        record_info.right_record_getter = &get_uint24;
        record_info.right_record_offset = 3;
    } else if (record_info.record_length == 7) {
        record_info.left_record_getter = &get_left_28_bit_record;
        record_info.right_record_getter = &get_right_28_bit_record;
        record_info.right_record_offset = 3;
    } else if (record_info.record_length == 8) {
        record_info.left_record_getter = &get_uint32;
        record_info.right_record_getter = &get_uint32;
        record_info.right_record_offset = 4;
    } else {
        assert(false);
    }

    return record_info;
}
```
似乎当时访问的是 settings.crashlytics.com:443

**Comment by laoyur** [comment]
@731704267 问题解决，是因为没有添加GeoLite2-Country.mmdb导致的
这个文件可以在这里下载：http://dev.maxmind.com/geoip/geoip2/geolite2/
