### ISSUE TITLE
自动断线的Bug

### ISSUE THREAD

**Issue by normalhh** [icodesign/Potatso#79]
#52 这个问题当初已经在这里写过。但是没人理

现在再说一遍，这个问题已经持续过很多个版本了。重装什么的并不能解决这个问题。
而且这个问题总是出现在Tumbletail这个应用上。可能是在一瞬间请求数过多导致断线。麻烦作者尽快排查一下问题原因。

**Comment by Yrp** [comment]
是的，也经常出现这个问题，急需解决。还没shadowrocket稳定
